/*
* Paul Joplin
* 04-07-2025
* CS - 210
* Project Three - Corner Grocer
*
* Project Three is a culmination of all concepts observed involving C++ in CS - 210.
* The client, Corner Grocer, has requested a text file analyzer to help with
* future changes in their produce department.
*
* The program reads a purchase log, calculates item frequency using maps, and displays results
* via a menu-driven interface with input validation.
*
* Modular design, reusable input handling, and file processing mirror practices from earlier assignments.
* 
* Tried to take my documentation to the next level!
*/

#include <iostream>
#include <fstream>

#include "GatherFileData.h"
#include "IOControls.h"

using namespace std;

int main() {
	// Instantiate file reader with input and backup file names.
	// Automatically triggers the read() logic inside the constructor.
	GatherFileData reader("ProduceList.txt", "frequency.dat");

	// Create IO controller to handle user interaction and validated input.
	IOControls controls;

	// Initiate the menu loop using the map generated by GatherFileData.
	controls.displayMenu(reader.GetFrequency());

	// Exit cleanly after option 4 is selected. 
	return 0;
}